name       : libwv
version    : 1.2.9
release    : 3
source     :
    - https://github.com/AbiWord/wv/archive/wv-1-2-9.tar.gz : effe7a2b5b81a3707c60894e7799f7c086fdec76549eb80c1e8fb835b873d2c9
license    : GPL-2.0-or-later
component  : programming.library
summary    : Library allowing access to Microsoft Word files
builddeps  :
    - pkgconfig(libgsf-1)
description: |
    wv is a library that allows access for programs to read and parse Microsoft Word documents.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
