name        : libwv
version     : 1.2.9
release     : 2
source      :
    - http://www.abisource.com/downloads/wv/1.2.9/wv-1.2.9.tar.gz : 4c730d3b325c0785450dd3a043eeb53e1518598c4f41f155558385dd2635c19d
license     :
    - GPL-2.0
summary     : Library allowing access to Microsoft Word files
builddeps   :
    - pkgconfig(libgsf-1)
description : |
    wv is a library that allows access for programs to read and parse Microsoft Word documents.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
